### ISSUE TITLE
Yakkety repos warnings and failure to install in Debian Testing

### ISSUE THREAD

**Issue by AVLinux** [KXStudio/KXStudio#10]
When updating Debian Testing (AV Linux) the Yakkety Repos package fails to complete install and gives this error message:

> Setting up kxstudio-repos (9.3.1~yakkety1) ...
> Warning: The postinst maintainerscript of the package kxstudio-repos
> Warning: seems to use apt-key (provided by apt) without depending on gnupg or gnupg2.
> Warning: This will BREAK in the future and should be fixed by the package maintainer(s).
> Note: Check first if apt-key functionality is needed at all - it probably isn't!
> Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package kxstudio-repos)
> OK
> Warning: The postinst maintainerscript of the package kxstudio-repos
> Warning: seems to use apt-key (provided by apt) without depending on gnupg or gnupg2.
> Warning: This will BREAK in the future and should be fixed by the package maintainer(s).
> Note: Check first if apt-key functionality is needed at all - it probably isn't!
> Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package kxstudio-repos)
> OK
> gpg: keybox '/tmp/tmp6n5xk65u/pubring.gpg' created

Console then just halts there indefinitely and then will not continue with the update/installation of any further packages. The only way I could get dpkg to finish it's business was to log out and manually remove the kxstudio-repos and kxstudio-repos-gcc5 packages from the system completely. This problem did not exist with the 9.3.0 repo packages.

**Comment by falkTX** [comment]
This is a breakage caused by a new rule of debian.
You already had 9.3.0 installed before so it was not triggered.

The error does not happen on Ubuntu 14.04 or 16.04 so I didn't see it.
I'm uploading 9.3.2 now with gnupg added as dependency.

**Comment by AVLinux** [comment]
Hi,

Thanks for the quick response!

Unfortunately the warnings have changed but the install still hangs at:
gpg: keybox '/tmp/tmp6n5xk65u/pubring.gpg' created

Full Output:

> Selecting previously unselected package kxstudio-repos.
> (Reading database ... 286023 files and directories currently installed.)
> Preparing to unpack .../0-kxstudio-repos_9.3.2~zesty1_all.deb ...
> Unpacking kxstudio-repos (9.3.2~zesty1) ...
> Selecting previously unselected package kxstudio-repos-gcc5.
> Preparing to unpack .../1-kxstudio-repos-gcc5_9.3.2~zesty1_all.deb ...
> Unpacking kxstudio-repos-gcc5 (9.3.2~zesty1) ...
> Setting up kxstudio-repos (9.3.2~zesty1) ...
> Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package kxstudio-repos)
> OK
> Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package kxstudio-repos)
> OK
> gpg: keybox '/tmp/tmp93zkrc66/pubring.gpg' created

Unfortunately at this point the console goes unresponsive, if Ctrl-C is pressed it warns that the system will be left in a broken state and synaptic can't be closed.

**Comment by falkTX** [comment]
wait, why is this installing the zesty package?
are you running ubuntu 17.04?

**Comment by AVLinux** [comment]
Debian Testing, that's what version appears in the repo

**Comment by falkTX** [comment]
something is strange then.
that version should only be possible if using the "ubuntus" ppa, which is not added if running under debian.
I'll investigate during the weekend.

**Comment by falkTX** [comment]
I found that the same issue happened with ubuntu-keyrings package, which was fixed in this changeset:
https://launchpadlibrarian.net/285357737/ubuntu-keyring_2016.09.01_2016.09.19.diff.gz

This is not a trivial task though. I'll do some testing in the following days...

**Comment by AVLinux** [comment]
Hi,

Any chance of reposting the previous 9.3.0 packages somewhere for now until you get time to fix this issue. Unfortunately the only recourse to allow APT and dpkg to work is to remove your repos completely for now.

**Comment by falkTX** [comment]
The old packages have exactly the same issue.
This is not caused by changes in the kxstudio-repos package, it's caused by a debian update.

FWIW I installed a debian testing chroot and was able to install the kxstudio-repos there.
It gave a warning when installing, but went on like normal.

**Comment by AVLinux** [comment]
Hmmm odd,

OK I did a fresh dist-upgrade and tried installing the repos again and still freezes at this point:

> gpg: keybox '/tmp/tmp93zkrc66/pubring.gpg' created

**Comment by falkTX** [comment]
This is fixed in kxstudio-repos v9.4.1.
Hopefully it doesn't cause issues for people in Debian 7 or Ubuntu 14.04.

Please confirm if fixes the issue for you.

**Comment by AVLinux** [comment]
Hi, the issue is fixed here, installation now completes as expected.

Thanks VERY much for your attention on this!

**Comment by falkTX** [comment]
Great, thanks for confirming!

Let me know if something similar ever happens again.
